@baseurl = http://localhost:3000/messages

### Messages findAll()
GET {{baseurl}}/
?limit=5
&offset=0
Authorization: Bearer 123456

### Messages findOne()
GET {{baseurl}}/10

### Messages Post()
POST {{baseurl}}
Content-Type: application/json

{
    "texto": "Oieeee",
    "deId": 1,
    "paraId": 2
  } 

### Messages Patch(id)
PATCH {{baseurl}}/14
Content-Type: application/json

{
    "texto": "Novo recado ATUALIZADO",
    "lido": true
  }

### Messages Remove(id)
DELETE {{baseurl}}/2