@baseurl = http://localhost:3000/persons

### Persons findAll()
GET {{baseurl}}/
?limit=100
&offset=100

### Persons findOne()
GET {{baseurl}}/2

### Persons Post()
POST {{baseurl}}
Content-Type: application/json

{
    "name": "Kako",
    "email": "kako@gmail.com",
    "password": "senha123"
  }

### Persons Patch(id)
PATCH {{baseurl}}/8
Content-Type: application/json

{
    "name": "Leonardo",
    "password": "outraSenha"
  }

### Persons Remove(id)
DELETE {{baseurl}}/5