@baseurl = http://localhost:3000/messages

### Messages findAll()
GET {{baseurl}}/
?limit=100
&offset=100

### Messages findOne()
GET {{baseurl}}/2

### Messages Post()
POST {{baseurl}}
Content-Type: application/json

{
    "texto": "Novo recado",
    "de": "Leonardo",
    "para": "João"
  }

### Messages Patch(id)
PATCH {{baseurl}}/2
Content-Type: application/json

{
    "texto": "Novo recado ATUALIZADO",
    "de": "Leonardo",
    "para": "João"
  }

### Messages Remove(id)
DELETE {{baseurl}}/2