@baseurl = http://localhost:3000/messages

### Messages findAll()
GET {{baseurl}}/
?limit=100
&offset=100

### Messages findOne()
GET {{baseurl}}/2

### Messages Post()
POST {{baseurl}}
Content-Type: application/json

{
    "texto": "Novo recado",
    "deId": 8,
    "paraId": 8
  }

### Messages Patch(id)
PATCH {{baseurl}}/14
Content-Type: application/json

{
    "texto": "Novo recado ATUALIZADO",
    "lido": true
  }

### Messages Remove(id)
DELETE {{baseurl}}/2